@extends('layouts.app')
@section('title', 'Inicio')
@section('content')
<div class="page-heading"><div><div class="eyebrow">UN NUEVO DÍA, MUCHAS POSIBILIDADES</div><h1>Hola, {{ explode(' ', auth()->user()->name)[0] }} <span style="font-size:24px">☀</span></h1><p>Así está tu tienda hoy. Todo lo que necesitás, a mano.</p></div><span class="badge badge-purple">@include('partials.icon', ['name' => 'clock']){{ $today->format('d/m/Y') }}</span></div>
<div class="welcome-banner"><div><div class="eyebrow">TU TIENDA, MÁS SIMPLE</div><h2>Pequeña tienda.<br>Grandes posibilidades.</h2><p>Ventas, productos y cuentas en un solo lugar.</p><div class="banner-tags"><span>✦ Simple de usar</span><span>♡ Pensado para vos</span><span>✓ Siempre organizado</span></div></div>@include('partials.shop')</div>
<div class="stats-grid">
    <div class="card stat-card"><div class="stat-top"><span>Ventas de hoy</span><span class="stat-icon">@include('partials.icon', ['name' => 'bag'])</span></div><div class="stat-number money">{{ \App\Services\Money::format($todaySalesCents) }}</div><div class="stat-bottom"><strong>{{ $salesCount }}</strong> {{ $salesCount === 1 ? 'venta registrada' : 'ventas registradas' }}</div></div>
    <div class="card stat-card"><div class="stat-top"><span>Compras de hoy</span><span class="stat-icon">@include('partials.icon', ['name' => 'cart'])</span></div><div class="stat-number money">{{ \App\Services\Money::format($todayPurchasesCents) }}</div><div class="stat-bottom">Abastecimiento de tu tienda</div></div>
    <a href="{{ route('accounts.index') }}" class="card stat-card"><div class="stat-top"><span>Saldo de clientes</span><span class="stat-icon">@include('partials.icon', ['name' => 'wallet'])</span></div><div class="stat-number money">{{ \App\Services\Money::format($customerBalanceCents) }}</div><div class="stat-bottom">Ver cuentas corrientes @include('partials.icon', ['name' => 'arrow', 'class' => 'text-purple'])</div></a>
    <a href="{{ route('products.index', ['low_stock' => 1]) }}" class="card stat-card"><div class="stat-top"><span>Stock bajo</span><span class="stat-icon">@include('partials.icon', ['name' => 'box'])</span></div><div class="stat-number">{{ $lowStockCount }} <span style="font-size:11px;font-weight:400;color:#a79ab5">{{ $lowStockCount === 1 ? 'producto' : 'productos' }}</span></div><div class="stat-bottom">Revisá qué necesitás reponer</div></a>
</div>
<div class="quick-actions"><a class="card quick-action" href="{{ route('sales.create') }}"><span class="quick-icon">@include('partials.icon', ['name' => 'plus'])</span><div><strong>Nueva venta</strong><small>Registrá en un instante</small></div>@include('partials.icon', ['name' => 'arrow'])</a><a class="card quick-action" href="{{ route('products.create') }}"><span class="quick-icon">@include('partials.icon', ['name' => 'box'])</span><div><strong>Agregar producto</strong><small>Hacé crecer tu catálogo</small></div>@include('partials.icon', ['name' => 'arrow'])</a><a class="card quick-action" href="{{ route('customers.create') }}"><span class="quick-icon">@include('partials.icon', ['name' => 'users'])</span><div><strong>Nuevo cliente</strong><small>Conectá con tus clientes</small></div>@include('partials.icon', ['name' => 'arrow'])</a></div>
<div class="dashboard-grid"><section class="card"><div class="card-header"><div><h2>Últimas ventas</h2><p>El movimiento más reciente de tu tienda.</p></div><a class="button-link" href="{{ route('sales.index') }}">Ver todas @include('partials.icon', ['name' => 'arrow'])</a></div>
@if($recentSales->isEmpty())@include('partials.empty', ['icon' => 'bag', 'heading' => 'Tu próxima venta empieza acá', 'description' => 'Agregá productos y registrá la primera venta de tu tienda.', 'url' => route('sales.create'), 'action' => 'Nueva venta'])
@else<div class="table-wrap"><table class="responsive-table"><thead><tr><th>Venta / Cliente</th><th>Fecha</th><th class="text-right">Total</th><th>Estado</th></tr></thead><tbody>@foreach($recentSales as $sale)<tr><td><a class="row-title" href="{{ route('sales.show', $sale) }}">{{ $sale->number }}</a><span class="row-sub">{{ $sale->customer?->name ?? 'Consumidor final' }}</span></td><td data-label="Fecha">{{ $sale->created_at->format('d/m · H:i') }}</td><td data-label="Total" class="text-right money text-bold">{{ \App\Services\Money::format($sale->total_cents) }}</td><td data-label="Estado"><span class="badge {{ $sale->status === 'completed' ? 'badge-green' : 'badge-red' }}"><span class="badge-dot"></span>{{ $sale->status === 'completed' ? 'Completada' : 'Anulada' }}</span></td></tr>@endforeach</tbody></table></div>@endif
</section><section class="card"><div class="card-header"><div><h2>Para reponer</h2><p>Mantené tu tienda siempre lista.</p></div><span class="badge badge-orange">{{ $lowStockCount }}</span></div>@if($lowStockProducts->isEmpty())@include('partials.empty', ['icon' => 'check', 'heading' => 'Stock al día', 'description' => 'Tus productos activos están por encima del stock mínimo.'])@else<div class="low-stock-list">@foreach($lowStockProducts as $product)<a href="{{ route('products.edit', $product) }}" class="low-stock-item"><div class="product-cell"><span class="product-placeholder">@include('partials.icon', ['name' => 'box'])</span><div><strong class="row-title">{{ $product->name }}</strong><span class="row-sub">{{ $product->sku }}</span></div></div><span class="badge badge-orange">{{ $product->stock }} u.</span></a>@endforeach</div><div class="low-stock-foot">@include('partials.icon', ['name' => 'alert']) Registrá una compra para sumar stock.</div>@endif</section></div>
@endsection
