@extends('layouts.app')
@section('title', 'Dashboard')
@push('head')
<script src="{{ asset('js/dashboard.js') }}" defer></script>
@endpush
@section('content')
@php
    $range = $dashboard['range'];
    $summary = $dashboard['summary'];
    $series = $dashboard['series'];
    $comparison = $summary['sales_change_percent'];
    $previousLabel = \Carbon\CarbonImmutable::parse($range['previous_from'])->format('d/m/Y').' al '.\Carbon\CarbonImmutable::parse($range['previous_to'])->format('d/m/Y');
    $salesComparison = $comparison === null ? ($summary['sales_cents'] > 0 ? 'Sin ventas en el período anterior' : 'Sin ventas en ambos períodos') : (($comparison > 0 ? '+' : '').number_format($comparison, 1, ',', '.').'% vs. período anterior');
    $maximum = max(array_merge([1], array_column($series, 'sales_cents'), array_column($series, 'previous_sales_cents')));
    $chartMax = $maximum > 1 ? (int) ceil($maximum / 100) * 100 : 100;
    $pointCount = count($series);
    $currentPoints = [];
    $previousPoints = [];
    foreach ($series as $index => $point) {
        $x = $pointCount > 1 ? 56 + ($index / ($pointCount - 1)) * 682 : 397;
        $currentPoints[] = round($x, 2).','.round(222 - ($point['sales_cents'] / $chartMax) * 190, 2);
        $previousPoints[] = round($x, 2).','.round(222 - ($point['previous_sales_cents'] / $chartMax) * 190, 2);
    }
    $paymentMax = max(array_merge([1], array_column($dashboard['payments'], 'total_cents')));
    $rankingMax = max(array_merge([1], array_column($dashboard['top_products'], 'quantity')));
@endphp
<div class="dashboard" data-dashboard data-endpoint="{{ url('/dashboard/data') }}" data-sale-create="{{ route('sales.create') }}" data-purchase-create="{{ route('purchases.create') }}" aria-busy="false">
    <div class="dashboard-hero"><div><div class="eyebrow">{{ $storeBrand['name'] ?? 'Chiqui Tienda' }} · RESUMEN DE TU NEGOCIO</div><h1>Hola, {{ explode(' ', auth()->user()->name)[0] }}.</h1><p>Los números claros. Tu próximo paso, a mano.</p></div><a class="button button-primary" href="{{ route('sales.create') }}">@include('partials.icon', ['name' => 'plus'])Nueva venta</a></div>
    <section class="dashboard-filter" aria-label="Elegir período">
        <nav class="period-tabs" aria-label="Períodos de análisis">
            @foreach(['today' => 'Hoy', 'yesterday' => 'Ayer', '7d' => '7 días', '30d' => '30 días', 'month' => 'Este mes'] as $preset => $label)
                <a href="{{ route('dashboard', ['preset' => $preset]) }}" data-preset="{{ $preset }}" class="{{ $range['preset'] === $preset ? 'active' : '' }}" @if($range['preset'] === $preset) aria-current="true" @endif>{{ $label }}</a>
            @endforeach
        </nav>
        <form class="date-range" method="GET" action="{{ route('dashboard') }}" data-range-form><input type="hidden" name="preset" value="custom"><div class="field"><label for="dashboard-from">Desde</label><input class="input" type="date" id="dashboard-from" name="from" value="{{ $range['from'] }}" required></div><span class="date-range-separator" aria-hidden="true">—</span><div class="field"><label for="dashboard-to">Hasta</label><input class="input" type="date" id="dashboard-to" name="to" value="{{ $range['to'] }}" required></div><button class="button button-secondary button-small" type="submit">Aplicar</button></form>
    </section>
    <div class="dashboard-status"><div><strong data-range-label>{{ $range['label'] }}</strong><span class="range-dates" data-range-dates>{{ \Carbon\CarbonImmutable::parse($range['from'])->format('d/m/Y') }} — {{ \Carbon\CarbonImmutable::parse($range['to'])->format('d/m/Y') }}</span><span class="live-status"><span class="status-dot"></span><span data-updated>Actualizado {{ $dashboard['updated_label'] }}</span></span></div><div class="dashboard-refresh"><label class="auto-refresh"><input type="checkbox" data-auto-refresh checked>Actualización automática</label><button class="button button-secondary button-small" type="button" data-refresh>@include('partials.icon', ['name' => 'clock'])Actualizar</button></div></div>
    <div class="alert alert-error" data-dashboard-error role="alert" hidden></div>
    <noscript><p class="dashboard-note">Los datos están actualizados al cargar la página. Usá los períodos o recargá para ver nuevos movimientos.</p></noscript>
    <section class="metric-grid" aria-label="Resultados del período">
        <article class="card metric-card"><div class="metric-top"><span>Ventas del período</span><span class="metric-icon">@include('partials.icon', ['name' => 'bag'])</span></div><div class="metric-value money" data-metric="sales_cents">{{ \App\Services\Money::format($summary['sales_cents']) }}</div><div class="metric-change {{ $comparison > 0 ? 'is-positive' : ($comparison < 0 ? 'is-negative' : '') }}" data-sales-comparison>{{ $salesComparison }}</div><p class="metric-meta" data-metric="sales_count">{{ $summary['sales_count'] }} {{ $summary['sales_count'] === 1 ? 'venta registrada' : 'ventas registradas' }}</p></article>
        <article class="card metric-card"><div class="metric-top"><span>Ticket promedio</span><span class="metric-icon">@include('partials.icon', ['name' => 'wallet'])</span></div><div class="metric-value money" data-metric="ticket_cents">{{ \App\Services\Money::format($summary['ticket_cents']) }}</div><p class="metric-meta">Importe promedio por venta</p></article>
        <article class="card metric-card"><div class="metric-top"><span>Unidades vendidas</span><span class="metric-icon">@include('partials.icon', ['name' => 'box'])</span></div><div class="metric-value" data-metric="units_sold">{{ number_format($summary['units_sold'], 0, ',', '.') }}</div><p class="metric-meta">Productos que salieron de tu tienda</p></article>
        <article class="card metric-card"><div class="metric-top"><span>Compras del período</span><span class="metric-icon">@include('partials.icon', ['name' => 'cart'])</span></div><div class="metric-value money" data-metric="purchases_cents">{{ \App\Services\Money::format($summary['purchases_cents']) }}</div><p class="metric-meta">Inversión en mercadería</p></article>
    </section>
    <div class="analytics-grid"><section class="card chart-card"><div class="card-header"><div><h2>Evolución de ventas</h2><p>Tu actividad diaria, con perspectiva.</p></div><div class="chart-switch" aria-label="Métrica del gráfico"><button type="button" class="active" data-chart-metric="money" aria-pressed="true">Importe</button><button type="button" data-chart-metric="count" aria-pressed="false">Cantidad</button></div></div><div class="card-body"><div class="chart-legend"><span><i class="legend-current"></i>Período elegido</span><span><i class="legend-previous"></i>Anterior <span data-previous-label>{{ $previousLabel }}</span></span></div>
        <div class="sales-chart" data-chart tabindex="0" role="group" aria-label="Ventas diarias. Usá las flechas para explorar los días." aria-describedby="chart-help">
            <svg viewBox="0 0 760 270" role="img" aria-label="Importe diario de ventas en pesos argentinos"><title>Evolución diaria de ventas</title>
                @for($tick = 0; $tick <= 4; $tick++)
                    <line x1="56" y1="{{ 222 - $tick * 47.5 }}" x2="738" y2="{{ 222 - $tick * 47.5 }}" stroke="currentColor" opacity=".09" />
                @endfor
                <polyline points="{{ implode(' ', $previousPoints) }}" fill="none" stroke="#9b968b" stroke-width="2" stroke-dasharray="5 5" />
                <polyline points="{{ implode(' ', $currentPoints) }}" fill="none" stroke="var(--brand, #c45130)" stroke-width="3" stroke-linejoin="round" stroke-linecap="round" />
                @if($pointCount === 1)<circle cx="397" cy="{{ round(222 - ($series[0]['sales_cents'] / $chartMax) * 190, 2) }}" r="5" fill="var(--brand, #c45130)" />@endif
                @if($pointCount > 0)<text x="56" y="251" fill="currentColor" font-size="11">{{ $series[0]['label'] }}</text><text x="738" y="251" fill="currentColor" font-size="11" text-anchor="end">{{ $series[$pointCount - 1]['label'] }}</text>@endif
            </svg>
            <div class="chart-tooltip" data-chart-tooltip hidden></div>
        </div><p class="chart-help" id="chart-help">Tocá un día para ver el detalle. Con teclado, usá ← y →.</p>
        <details class="chart-data"><summary>Ver datos del gráfico</summary><div class="table-wrap"><table><caption class="sr-only">Ventas diarias y comparación por días equivalentes del período anterior</caption><thead><tr><th>Fecha</th><th class="text-right">Ventas</th><th class="text-right">Importe</th><th class="text-right">Ventas anteriores</th><th class="text-right">Importe anterior</th></tr></thead><tbody data-series-table>@foreach($series as $point)<tr><td>{{ $point['label'] }}</td><td class="text-right">{{ $point['sales_count'] }}</td><td class="text-right money">{{ \App\Services\Money::format($point['sales_cents']) }}</td><td class="text-right">{{ $point['previous_sales_count'] }}</td><td class="text-right money">{{ \App\Services\Money::format($point['previous_sales_cents']) }}</td></tr>@endforeach</tbody></table></div></details>
    </div></section>
    <section class="card"><div class="card-header"><div><h2>Formas de pago</h2><p>Cómo se registraron tus ventas.</p></div>@include('partials.icon', ['name' => 'wallet'])</div><div class="card-body"><div class="payment-list" data-payments>@foreach($dashboard['payments'] as $payment)<div class="payment-row"><div class="payment-head"><span>{{ $payment['label'] }}</span><strong class="money">{{ \App\Services\Money::format($payment['total_cents']) }}</strong></div><div class="payment-bar"><span style="width:{{ round($payment['total_cents'] / $paymentMax * 100, 2) }}%"></span></div><small>{{ $payment['count'] }} {{ $payment['count'] === 1 ? 'venta' : 'ventas' }}</small></div>@endforeach</div><p class="dashboard-note">Cuenta corriente registra deuda del cliente; no representa dinero cobrado.</p></div></section></div>
    <div class="dashboard-secondary"><section class="card"><div class="card-header"><div><h2>Los más vendidos</h2><p>Productos que marcaron el período.</p></div><a class="button-link" href="{{ route('products.index') }}">Ver productos @include('partials.icon', ['name' => 'arrow'])</a></div><div data-ranking>@if(count($dashboard['top_products']) === 0)<div class="dashboard-empty"><span class="empty-icon">@include('partials.icon', ['name' => 'box'])</span><h3>Tu ranking está por empezar</h3><p>Los productos aparecerán acá cuando registres ventas en este período.</p></div>@else <div class="ranking-list">@foreach($dashboard['top_products'] as $index => $product)<a class="ranking-row" href="{{ $product['url'] }}"><span class="ranking-position">{{ $index + 1 }}</span><div class="ranking-main"><strong>{{ $product['name'] }}</strong><small>{{ $product['sku'] }}</small><div class="ranking-bar"><span style="width:{{ round($product['quantity'] / $rankingMax * 100, 2) }}%"></span></div></div><div class="ranking-value"><strong>{{ number_format($product['quantity'], 0, ',', '.') }} u.</strong><small class="money">{{ \App\Services\Money::format($product['total_cents']) }}</small></div></a>@endforeach</div>@endif</div></section>
    <section class="card dashboard-summary"><div class="card-header"><div><h2>Hoy, en tu tienda</h2><p>Saldos y stock actuales, para cualquier período.</p></div></div><div class="summary-list"><a class="summary-row" href="{{ route('accounts.index') }}"><span class="summary-icon">@include('partials.icon', ['name' => 'users'])</span><div><span>Saldo de clientes</span><strong class="money" data-metric="customer_balance_cents">{{ \App\Services\Money::format($summary['customer_balance_cents']) }}</strong><small>Débitos menos pagos y créditos</small></div>@include('partials.icon', ['name' => 'arrow'])</a><a class="summary-row" href="{{ route('accounts.index') }}"><span class="summary-icon">@include('partials.icon', ['name' => 'truck'])</span><div><span>Saldo de proveedores</span><strong class="money" data-metric="supplier_balance_cents">{{ \App\Services\Money::format($summary['supplier_balance_cents']) }}</strong><small>Deuda registrada menos pagos</small></div>@include('partials.icon', ['name' => 'arrow'])</a><a class="summary-row" href="{{ route('products.index', ['low_stock' => 1]) }}"><span class="summary-icon">@include('partials.icon', ['name' => 'alert'])</span><div><span>Productos para reponer</span><strong data-metric="low_stock_count">{{ $summary['low_stock_count'] }}</strong><small>Stock igual o menor al mínimo</small></div>@include('partials.icon', ['name' => 'arrow'])</a></div></section></div>
    <div class="dashboard-lower"><section class="card"><div class="card-header"><div><h2>Últimas ventas del período</h2><p>Operaciones registradas, sin las anuladas.</p></div><a class="button-link" href="{{ route('sales.index') }}">Ver todas @include('partials.icon', ['name' => 'arrow'])</a></div><div data-recent-sales>@if(count($dashboard['recent_sales']) === 0)<div class="dashboard-empty"><span class="empty-icon">@include('partials.icon', ['name' => 'bag'])</span><h3>Sin ventas en este período</h3><p>Cambiá las fechas o registrá tu próxima venta.</p><a class="button button-primary button-small" href="{{ route('sales.create') }}">Nueva venta</a></div>@else <div class="table-wrap"><table class="responsive-table"><thead><tr><th>Venta / Cliente</th><th>Fecha</th><th>Pago</th><th class="text-right">Total</th></tr></thead><tbody>@foreach($dashboard['recent_sales'] as $sale)<tr><td><a class="row-title" href="{{ $sale['url'] }}">{{ $sale['number'] }}</a><span class="row-sub">{{ $sale['customer'] }}</span></td><td data-label="Fecha">{{ $sale['date'] }}</td><td data-label="Pago"><span class="badge badge-gray">{{ $sale['payment_label'] }}</span></td><td class="text-right money text-bold" data-label="Total">{{ \App\Services\Money::format($sale['total_cents']) }}</td></tr>@endforeach</tbody></table></div>@endif</div></section>
    <section class="card"><div class="card-header"><div><h2>Para reponer</h2><p>Existencias actuales de tu catálogo.</p></div><span class="badge badge-orange" data-stock-badge>{{ $summary['low_stock_count'] }}</span></div><div data-low-stock>@if(count($dashboard['low_stock']) === 0)<div class="dashboard-empty"><span class="empty-icon">@include('partials.icon', ['name' => 'check'])</span><h3>Sin alertas de stock</h3><p>Tu catálogo no tiene productos activos por debajo del mínimo.</p></div>@else <div class="low-stock-list">@foreach($dashboard['low_stock'] as $product)<a class="low-stock-item" href="{{ $product['url'] }}"><div><strong class="row-title">{{ $product['name'] }}</strong><span class="row-sub">{{ $product['sku'] }} · mínimo {{ $product['min_stock'] }}</span></div><span class="badge badge-orange">{{ $product['stock'] }} u.</span></a>@endforeach</div><div class="low-stock-foot"><a href="{{ route('purchases.create') }}">Registrá una compra para sumar stock. @include('partials.icon', ['name' => 'arrow'])</a></div>@endif</div></section></div>
    <p class="dashboard-note dashboard-footnote">Importes en pesos argentinos · Ventas y compras registradas · Horario {{ $range['time_zone'] }}</p>
</div>
<script type="application/json" id="dashboard-data">{!! json_encode($dashboard, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR) !!}</script>
@endsection
