@extends('shop.layout')
@section('title', 'Mi carrito')
@section('content')
<section class="shop-container shop-page"><div class="shop-page-heading"><div><p class="shop-eyebrow">TU PRÓXIMA COMPRA</p><h1>Mi carrito <span class="shop-count">{{ $cartCount }}</span></h1><p>Revisá tus productos antes de confirmar el pedido.</p></div><a class="shop-text-link" href="{{ route('shop.index') }}#productos">Seguir comprando @include('partials.icon', ['name' => 'arrow'])</a></div>
@if(empty($cart))<div class="shop-empty">@include('partials.icon', ['name' => 'bag'])<h2>Tu carrito está esperando una buena idea</h2><p>Elegí tus productos y encontralos acá.</p><a class="shop-button" href="{{ route('shop.index') }}#productos">Explorar productos @include('partials.icon', ['name' => 'arrow'])</a></div>
@else
@php($canCheckout = collect($cart)->every(fn($entry) => $entry['available']))
<div class="shop-checkout-grid"><div><section class="shop-card shop-cart-items" aria-label="Productos del carrito">@foreach($cart as $entry)@php($product = $entry['product'])<article class="shop-cart-item"><div class="shop-cart-photo">@if($product?->image_path)<img src="{{ asset('storage/'.$product->image_path) }}" alt="{{ $product->name }}" width="600" height="600">@else@include('partials.icon', ['name' => 'box'])@endif</div><div class="shop-cart-product"><span class="shop-product-sku">SKU {{ $product?->sku }}</span><h2>{{ $product?->name ?? 'Producto no disponible' }}</h2><p>{{ \App\Services\Money::format($entry['unit_price_cents']) }} por unidad</p>@unless($entry['available'])<span class="shop-stock-error">Producto o cantidad no disponible. Revisá el stock o quitá el producto.</span>@endunless</div><form method="POST" action="{{ route('shop.cart.update', $entry['product_id']) }}" class="shop-cart-quantity">@csrf @method('PATCH')<label for="quantity-{{ $entry['product_id'] }}">Cantidad</label><div><input id="quantity-{{ $entry['product_id'] }}" name="quantity" type="number" min="1" max="100" value="{{ $entry['quantity'] }}" inputmode="numeric" required><button type="submit" aria-label="Actualizar cantidad de {{ $product?->name }}" title="Actualizar cantidad">@include('partials.icon', ['name' => 'refresh'])</button></div></form><strong class="shop-cart-line-price">{{ \App\Services\Money::format($entry['subtotal_cents']) }}</strong><form method="POST" action="{{ route('shop.cart.remove', $entry['product_id']) }}" class="shop-cart-remove">@csrf @method('DELETE')<button type="submit" aria-label="Quitar {{ $product?->name ?? 'producto' }} del carrito" title="Quitar producto">@include('partials.icon', ['name' => 'trash'])</button></form></article>@endforeach</section>
<section class="shop-card shop-delivery-card"><h2>@include('partials.icon', ['name' => 'box']) ¿Cómo recibís tu pedido?</h2><div class="shop-delivery-option"><span>@include('partials.icon', ['name' => 'check'])</span><div><strong>Retiro a coordinar con la tienda</strong><p>Esperá la confirmación de disponibilidad antes de acercarte. Coordinamos el lugar y el horario después de recibir tu pedido.</p></div><b>Sin cargo</b></div><p class="shop-integration-note">Los envíos con logística y los pagos online todavía no están habilitados. El pedido no realiza un cobro automático.</p></section>
</div><aside class="shop-card shop-checkout-summary"><p class="shop-eyebrow">YA CASI ES TUYO</p><h2>Resumen de compra</h2><div class="shop-total-row"><span>Productos ({{ $cartCount }})</span><strong>{{ \App\Services\Money::format($cartTotalCents) }}</strong></div><div class="shop-total-row"><span>Retiro a coordinar</span><span>Sin cargo</span></div><div class="shop-total-row shop-total-final"><span>Total</span><strong>{{ \App\Services\Money::format($cartTotalCents) }}</strong></div>
@auth<form method="POST" action="{{ route('shop.orders.store') }}" class="shop-order-form">@csrf<input type="hidden" name="request_id" value="{{ $requestId }}"><input type="hidden" name="delivery_method" value="pickup"><div class="shop-checkout-identity">@include('partials.icon', ['name' => 'users'])<span><strong>{{ auth()->user()->name }}</strong><small>{{ auth()->user()->email }}</small></span></div><label class="shop-field" for="contact-phone">Teléfono de contacto <span>(opcional)</span></label><input id="contact-phone" name="address[phone]" type="tel" autocomplete="tel" maxlength="50" value="{{ old('address.phone') }}"><label class="shop-field shop-notes-label" for="order-notes">Comentario para la tienda <span>(opcional)</span></label><textarea id="order-notes" name="notes" rows="3" maxlength="2000" placeholder="Dejanos un dato que ayude a coordinar tu pedido.">{{ old('notes') }}</textarea><div class="shop-payment-note">@include('partials.icon', ['name' => 'card'])<span><strong>Pago pendiente, a coordinar</strong><small>Confirmar el pedido reserva el stock y deja el pago pendiente. No se realiza ningún cobro automático.</small></span></div>@unless($canCheckout)<p class="shop-stock-error" role="alert">Revisá los productos no disponibles para continuar.</p>@endunless<button class="shop-button shop-button-wide" type="submit" @disabled(!$canCheckout)>Confirmar pedido @include('partials.icon', ['name' => 'arrow'])</button><p class="shop-checkout-footnote">Podés consultar el pedido desde Mis compras.</p></form>
@else<div class="shop-payment-note">@include('partials.icon', ['name' => 'users'])<span><strong>Ingresá para confirmar tu pedido</strong><small>Tu carrito queda guardado en esta sesión. Con tu cuenta podés consultar todas tus compras.</small></span></div><a class="shop-button shop-button-wide" href="{{ route('login') }}">Ingresar a mi cuenta @include('partials.icon', ['name' => 'arrow'])</a>@endauth
</aside></div>
@endif</section>
@endsection
