@extends('shop.layout')
@section('title', 'Tienda')
@section('content')
<section class="shop-container shop-hero" aria-label="Novedades de la tienda">
    <div class="shop-hero-main"><div class="shop-hero-copy"><span class="shop-hero-kicker">RENOVÁ TU SETUP</span><h1>Más tecnología.<br><strong>Más posibilidades.</strong></h1><p>Todo para tu PC, tu trabajo<br>y tus mejores partidas.</p><a class="shop-button" href="#productos">Encontrá lo que necesitás @include('partials.icon', ['name' => 'arrow'])</a><span class="shop-hero-caption">COMPONENTES · ACCESORIOS · PERIFÉRICOS</span></div><div class="shop-tech-art" aria-hidden="true"><div class="shop-art-orbit"></div><div class="shop-art-monitor"><div class="shop-art-screen"><span>{{ mb_strtoupper(mb_substr(app('store.brand')['name'], 0, 1)) }}<sup>+</sup></span><small>MAKE IT HAPPEN.</small></div><div class="shop-art-neck"></div><div class="shop-art-foot"></div></div><div class="shop-art-keyboard">@for($key = 0; $key < 42; $key++)<i></i>@endfor</div><div class="shop-art-mouse"></div></div></div>
    <div class="shop-hero-side"><a class="shop-mini-banner shop-banner-dark" href="#productos"><small>TODO PARA TU EQUIPO</small><strong>Tu espacio.<br>Tus reglas.</strong><span>Explorá el catálogo @include('partials.icon', ['name' => 'arrow'])</span><div aria-hidden="true">@include('partials.icon', ['name' => 'box'])</div></a><a class="shop-mini-banner shop-banner-light" href="#categorias"><small>HACÉ MÁS, TODOS LOS DÍAS</small><strong>Conectá con<br>lo que importa.</strong><span>Elegí tus accesorios @include('partials.icon', ['name' => 'arrow'])</span><div aria-hidden="true">@include('partials.icon', ['name' => 'grid'])</div></a></div>
</section>
<section class="shop-container shop-benefits" aria-label="Cómo comprar"><div>@include('partials.icon', ['name' => 'box'])<span><strong>Retiro a coordinar</strong><small>Consultá disponibilidad al pedir</small></span></div><div>@include('partials.icon', ['name' => 'card'])<span><strong>Pago a coordinar</strong><small>El pedido no genera un cobro</small></span></div><div>@include('partials.icon', ['name' => 'check'])<span><strong>Comprá con confianza</strong><small>Precios y stock actualizados</small></span></div><div>@include('partials.icon', ['name' => 'bag'])<span><strong>Tus compras, a un clic</strong><small>Seguí cada pedido en tu cuenta</small></span></div></section>
@if($categories->isNotEmpty())
<section id="categorias" class="shop-container shop-section"><div class="shop-section-heading"><div><p class="shop-eyebrow">ARMÁ TU MUNDO</p><h2>Encontrá tu próxima mejora</h2></div><a class="shop-text-link" href="{{ route('shop.index') }}#productos">Ver todos los productos @include('partials.icon', ['name' => 'arrow'])</a></div><div class="shop-category-tiles">@foreach($categories as $category)<a href="{{ route('shop.index', ['category' => $category]) }}#productos" class="{{ request('category') === $category ? 'is-active' : '' }}">@include('partials.icon', ['name' => ['box', 'grid', 'card', 'bag', 'print', 'truck'][$loop->index % 6]])<strong>{{ $category }}</strong><span>Explorar @include('partials.icon', ['name' => 'arrow'])</span></a>@endforeach</div></section>
@endif
<section id="productos" class="shop-container shop-section shop-catalog"><div class="shop-section-heading"><div><p class="shop-eyebrow">TECNOLOGÍA QUE VA CON VOS</p><h2>{{ request('q') ? 'Resultados para “'.request('q').'”' : (request('category') ?: 'Elegí tu próximo producto') }}</h2></div><span class="shop-result-count">{{ $products->total() }} productos</span></div><form method="GET" action="{{ route('shop.index') }}#productos" class="shop-catalog-filter"><div class="shop-filter-search">@include('partials.icon', ['name' => 'search'])<label class="shop-sr-only" for="catalog-search">Nombre o SKU</label><input id="catalog-search" name="q" type="search" value="{{ request('q') }}" placeholder="Buscar por nombre o SKU"></div><label class="shop-sr-only" for="catalog-category">Categoría</label><select id="catalog-category" name="category"><option value="">Todas las categorías</option>@foreach($categories as $category)<option value="{{ $category }}" @selected(request('category') === $category)>{{ $category }}</option>@endforeach</select><button class="shop-button shop-button-light" type="submit">Filtrar</button>@if(request('q') || request('category'))<a class="shop-text-link" href="{{ route('shop.index') }}#productos">Limpiar</a>@endif</form>
@if($products->isEmpty())<div class="shop-empty">@include('partials.icon', ['name' => 'search'])<h3>No encontramos productos</h3><p>Probá otra búsqueda o seleccioná una categoría diferente.</p><a class="shop-button" href="{{ route('shop.index') }}#productos">Ver todo el catálogo</a></div>
@else<div class="shop-product-grid">@foreach($products as $product)<article class="shop-product-card"><div class="shop-product-image">@if($product->image_path)<img src="{{ asset('storage/'.$product->image_path) }}" alt="{{ $product->name }}" width="600" height="600" loading="lazy">@else<div class="shop-image-placeholder">@include('partials.icon', ['name' => 'box'])</div>@endif<span class="shop-product-label">{{ $product->category ?: 'PRODUCTO' }}</span></div><div class="shop-product-info"><span class="shop-product-sku">SKU {{ $product->sku }}</span><h3>{{ $product->name }}</h3><span class="shop-product-stock {{ $product->stock < 1 ? 'is-unavailable' : '' }}"><i></i>{{ $product->stock > 0 ? 'En stock' : 'Sin stock' }}</span><p class="shop-product-price">{{ \App\Services\Money::format($product->price_cents) }}</p><small class="shop-price-note">Precio final</small>@if($product->description)<details class="shop-product-details"><summary>Ver descripción @include('partials.icon', ['name' => 'chevron'])</summary><p>{{ $product->description }}</p></details>@endif<form method="POST" action="{{ route('shop.cart.add', $product) }}">@csrf<input type="hidden" name="quantity" value="1"><button class="shop-add-button" type="submit" @disabled($product->stock < 1)>@include('partials.icon', ['name' => 'bag']){{ $product->stock > 0 ? 'Agregar al carrito' : 'No disponible' }}@include('partials.icon', ['name' => 'plus'])</button></form></div></article>@endforeach</div>@include('shop.partials.pagination', ['paginator' => $products])@endif
</section>
@endsection
