@extends('shop.layout')
@section('title', 'Mis compras')
@section('content')
<section class="shop-container shop-page"><div class="shop-page-heading"><div><p class="shop-eyebrow">TU CUENTA</p><h1>Mis compras</h1><p>El detalle y el estado de cada pedido, en un solo lugar.</p></div><a class="shop-text-link" href="{{ route('shop.index') }}">Volver a la tienda @include('partials.icon', ['name' => 'arrow'])</a></div><div class="shop-account-grid"><aside class="shop-card shop-profile"><span class="shop-profile-avatar">{{ mb_strtoupper(mb_substr(auth()->user()->name, 0, 1)) }}</span><h2>Hola, {{ \Illuminate\Support\Str::before(auth()->user()->name, ' ') }}</h2><p>{{ auth()->user()->email }}</p><nav aria-label="Mi cuenta"><a class="is-active" href="{{ route('shop.orders.index') }}" aria-current="page">@include('partials.icon', ['name' => 'bag']) Mis compras <span>{{ $orders->total() }}</span></a><a href="{{ route('shop.cart.index') }}">@include('partials.icon', ['name' => 'cart']) Mi carrito</a>@if(auth()->user()->isAdmin())<a href="{{ route('dashboard') }}">@include('partials.icon', ['name' => 'grid']) Administración</a>@endif</nav><form method="POST" action="{{ route('logout') }}">@csrf<button class="shop-profile-logout" type="submit">@include('partials.icon', ['name' => 'logout']) Cerrar sesión</button></form></aside><div class="shop-orders-list">
@if($orders->isEmpty())<div class="shop-card shop-empty">@include('partials.icon', ['name' => 'bag'])<h2>Tu primera compra empieza acá</h2><p>Cuando confirmes un pedido, vas a encontrar todos sus detalles en esta sección.</p><a class="shop-button" href="{{ route('shop.index') }}#productos">Explorar productos @include('partials.icon', ['name' => 'arrow'])</a></div>
@else
@foreach($orders as $order)<article class="shop-card shop-order-card"><header><div><span class="shop-eyebrow">PEDIDO {{ $order->number }}</span><time datetime="{{ $order->created_at->toIso8601String() }}">{{ $order->created_at->format('d/m/Y · H:i') }}</time></div>@include('shop.partials.status', ['status' => $order->status])</header><div class="shop-order-preview"><div class="shop-order-preview-images">@foreach(array_slice($order->items, 0, 3) as $item)<div>@if($item['image_path'] ?? null)<img src="{{ asset('storage/'.$item['image_path']) }}" alt="{{ $item['name'] }}" width="600" height="600" loading="lazy">@else@include('partials.icon', ['name' => 'box'])@endif</div>@endforeach @if(count($order->items) > 3)<span>+{{ count($order->items) - 3 }}</span>@endif</div><div class="shop-order-preview-text"><h2>{{ $order->items[0]['name'] ?? 'Tu pedido' }}</h2><p>{{ collect($order->items)->sum('quantity') }} {{ collect($order->items)->sum('quantity') === 1 ? 'unidad' : 'unidades' }} · Retiro a coordinar</p></div><strong class="shop-order-total">{{ \App\Services\Money::format($order->total_cents) }}</strong></div><footer><span class="shop-payment-status {{ $order->payment_status === 'confirmed' ? 'is-confirmed' : '' }}">@include('partials.icon', ['name' => 'card']){{ $order->payment_status === 'confirmed' ? 'Pago confirmado manualmente' : 'Pago pendiente' }}</span><a class="shop-button shop-button-light" href="{{ route('shop.orders.show', $order) }}">Ver pedido @include('partials.icon', ['name' => 'arrow'])</a></footer></article>@endforeach
@include('shop.partials.pagination', ['paginator' => $orders])
@endif
</div></div></section>
@endsection
