@extends('shop.layout')
@section('title', 'Pedido '.$order->number)
@section('content')
@php
    $steps = ['pending' => 'Pedido recibido', 'preparing' => 'Preparando', 'shipped' => 'Listo para retirar', 'delivered' => 'Entregado'];
    $currentStep = array_search($order->status, array_keys($steps), true);
@endphp
<section class="shop-container shop-page"><a class="shop-back-link" href="{{ route('shop.orders.index') }}">@include('partials.icon', ['name' => 'back']) Mis compras</a><div class="shop-page-heading"><div><p class="shop-eyebrow">EL DETALLE DE TU COMPRA</p><h1>Pedido {{ $order->number }}</h1><p>Creado el {{ $order->created_at->format('d/m/Y') }} a las {{ $order->created_at->format('H:i') }}.</p></div>@include('shop.partials.status', ['status' => $order->status])</div><div class="shop-checkout-grid"><div>
<section class="shop-card shop-order-progress"><h2>Estado del pedido</h2>@if($order->status === 'cancelled')<div class="shop-cancelled-note">@include('partials.icon', ['name' => 'close'])<div><strong>Este pedido fue cancelado</strong><p>Contactá a la tienda si necesitás más información.</p></div></div>@else<ol class="shop-progress-steps">@foreach($steps as $step => $label)<li class="{{ $currentStep !== false && $loop->index < $currentStep ? 'is-complete' : '' }} {{ $step === $order->status ? 'is-current' : '' }}"><span>@if($currentStep !== false && $loop->index < $currentStep)@include('partials.icon', ['name' => 'check'])@else{{ $loop->iteration }}@endif</span><strong>{{ $label }}</strong></li>@endforeach</ol><p class="shop-order-next">{{ match($order->status) { 'pending' => 'Recibimos tu pedido y reservamos el stock. La tienda coordinará el pago con vos.', 'preparing' => 'Estamos preparando los productos. Esperá la confirmación antes de acercarte.', 'shipped' => 'Tu pedido está listo. Coordiná con la tienda el lugar y el horario del retiro.', 'delivered' => 'El pedido figura como entregado. ¡Gracias por tu compra!', default => 'Consultá a la tienda para conocer la próxima actualización.' } }}</p>@endif</section>
<section class="shop-card shop-order-products"><div class="shop-card-heading"><h2>Productos de tu pedido</h2><span>{{ collect($order->items)->sum('quantity') }} unidades</span></div>@foreach($order->items as $item)<article class="shop-order-product"><div class="shop-cart-photo">@if($item['image_path'] ?? null)<img src="{{ asset('storage/'.$item['image_path']) }}" alt="{{ $item['name'] }}" width="600" height="600">@else@include('partials.icon', ['name' => 'box'])@endif</div><div><span class="shop-product-sku">SKU {{ $item['sku'] }}</span><h3>{{ $item['name'] }}</h3><p>{{ $item['quantity'] }} × {{ \App\Services\Money::format($item['unit_price_cents']) }}</p></div><strong>{{ \App\Services\Money::format($item['quantity'] * $item['unit_price_cents']) }}</strong></article>@endforeach</section>
@if($order->notes)<section class="shop-card shop-order-notes"><h2>Tu comentario</h2><p>{{ $order->notes }}</p></section>@endif
</div><aside class="shop-card shop-order-summary"><h2>Resumen del pedido</h2><div class="shop-total-row"><span>Productos</span><strong>{{ \App\Services\Money::format($order->total_cents) }}</strong></div><div class="shop-total-row"><span>Retiro a coordinar</span><span>Sin cargo</span></div><div class="shop-total-row shop-total-final"><span>Total</span><strong>{{ \App\Services\Money::format($order->total_cents) }}</strong></div><div class="shop-order-info"><span>@include('partials.icon', ['name' => 'users'])</span><div><strong>{{ auth()->user()->name }}</strong><p>{{ auth()->user()->email }}</p>@if($order->address['phone'] ?? null)<p>{{ $order->address['phone'] }}</p>@endif</div></div><div class="shop-order-info"><span>@include('partials.icon', ['name' => 'card'])</span><div><strong>{{ $order->payment_status === 'confirmed' ? 'Pago confirmado manualmente' : 'Pago pendiente' }}</strong><p>{{ $order->payment_status === 'confirmed' ? 'La tienda registró la recepción del pago. Esta confirmación no realizó un cobro online.' : 'Coordiná el pago con la tienda. Confirmar el pedido no generó un cobro automático.' }}</p>@if($order->payment_confirmed_at)<small>Registrado el {{ $order->payment_confirmed_at->format('d/m/Y · H:i') }}</small>@endif</div></div><div class="shop-order-info"><span>@include('partials.icon', ['name' => 'box'])</span><div><strong>Retiro a coordinar</strong><p>No se generó un envío contratado. Esperá la confirmación antes de acercarte.</p></div></div>@if($order->tracking_code || $order->tracking_url)<div class="shop-order-info"><span>@include('partials.icon', ['name' => 'truck'])</span><div><strong>Información de seguimiento</strong>@if($order->tracking_code)<p>Código: {{ $order->tracking_code }}</p>@endif @if($order->tracking_url)<a class="shop-text-link" href="{{ $order->tracking_url }}" target="_blank" rel="noopener noreferrer">Abrir seguimiento @include('partials.icon', ['name' => 'arrow'])</a>@endif</div></div>@endif<a class="shop-button shop-button-light shop-button-wide" href="{{ route('shop.index') }}#productos">Seguir explorando @include('partials.icon', ['name' => 'arrow'])</a></aside></div></section>
@endsection
