@extends('layouts.app')
@php($isCustomer = $kind === 'customers')
@php($singular = $isCustomer ? 'cliente' : 'proveedor')
@section('title', ($contact->exists ? 'Editar ' : 'Nuevo ').$singular)
@section('content')
<div class="page-heading"><div><div class="eyebrow">{{ $title }}</div><h1>{{ $contact->exists ? 'Editar ' : 'Nuevo ' }}{{ $singular }}</h1><p>Los datos necesarios para una relación bien organizada.</p></div><a class="button button-secondary" href="{{ route($kind.'.index') }}">@include('partials.icon', ['name' => 'back'])Volver</a></div>
<form method="POST" action="{{ $contact->exists ? route($kind.'.update', $contact) : route($kind.'.store') }}">@csrf @if($contact->exists)@method('PUT')@endif<div class="form-layout"><div class="form-main"><section class="card"><div class="card-header"><div><h2>Datos del {{ $singular }}</h2><p>Los campos con * son obligatorios.</p></div><span class="stat-icon">@include('partials.icon', ['name' => $isCustomer ? 'users' : 'truck'])</span></div><div class="card-body"><div class="form-grid">
<div class="field span-2"><label for="name">Nombre o razón social <span class="required">*</span></label><input class="input" id="name" name="name" value="{{ old('name', $contact->name) }}" maxlength="200" required placeholder="Ej. María Gómez / Mi Distribuidora">@error('name')<span class="field-error">{{ $message }}</span>@enderror</div>
<div class="field"><label for="document">DNI / CUIT</label><input class="input" id="document" name="document" value="{{ old('document', $contact->document) }}" maxlength="30" placeholder="Documento o identificación fiscal"></div>
<div class="field"><label for="phone">Teléfono</label><input class="input" id="phone" name="phone" type="tel" value="{{ old('phone', $contact->phone) }}" maxlength="40" placeholder="Ej. +54 11 1234 5678"></div>
<div class="field span-2"><label for="email">Correo electrónico</label><input class="input" id="email" name="email" type="email" value="{{ old('email', $contact->email) }}" maxlength="255" placeholder="nombre@correo.com"></div>
<div class="field span-2"><label for="address">Dirección</label><input class="input" id="address" name="address" value="{{ old('address', $contact->address) }}" maxlength="500" placeholder="Calle, número y localidad"></div>
@if($isCustomer)<div class="field span-2"><label for="credit_limit">Límite de cuenta corriente</label><input class="input" id="credit_limit" name="credit_limit" type="number" inputmode="decimal" min="0" max="999999999.99" step="0.01" value="{{ old('credit_limit', isset($contact->credit_limit_cents) ? number_format($contact->credit_limit_cents / 100, 2, '.', '') : '') }}" placeholder="Sin límite"><p class="hint">Importe en pesos. Ingresá 0 o dejalo vacío para permitir ventas sin un límite de crédito.</p></div>@endif
<div class="field span-2"><label for="notes">Notas</label><textarea id="notes" name="notes" rows="3" placeholder="Información útil para tu tienda">{{ old('notes', $contact->notes) }}</textarea></div>
<div class="span-2 toggle-field"><input type="hidden" name="active" value="0"><input id="active" type="checkbox" name="active" value="1" @checked(old('active', $contact->exists ? $contact->active : true))><label for="active">{{ $isCustomer ? 'Cliente activo' : 'Proveedor activo' }}<small>Disponible para registrar nuevas operaciones.</small></label></div>
</div></div></section><div class="form-actions"><a class="button button-secondary" href="{{ route($kind.'.index') }}">Cancelar</a><button class="button button-primary" type="submit">@include('partials.icon', ['name' => 'check'])Guardar {{ $singular }}</button></div></div><aside><div class="info-panel">@include('partials.icon', ['name' => 'wallet'])<h3>Su cuenta, siempre clara</h3><p>{{ $isCustomer ? 'Las ventas a cuenta aumentan el saldo. Los cobros registrados lo reducen.' : 'Las compras a cuenta aumentan el saldo. Los pagos registrados lo reducen.' }}</p><p style="margin-top:12px">Podés consultar todos los movimientos desde la ficha del {{ $singular }}.</p></div></aside></div></form>
@endsection
