@extends('layouts.app')
@section('title', $title)
@section('content')
@php($isCustomer = $kind === 'customers')
<div class="page-heading"><div><div class="eyebrow">{{ $isCustomer ? 'LAS PERSONAS DETRÁS DE CADA VENTA' : 'QUIENES ACOMPAÑAN TU NEGOCIO' }}</div><h1>{{ $title }}</h1><p>{{ $isCustomer ? 'Sus datos, sus compras y sus cuentas, siempre a mano.' : 'Organizá contactos, compras y cuentas corrientes.' }}</p></div><a class="button button-primary" href="{{ route($kind.'.create') }}">@include('partials.icon', ['name' => 'plus']){{ $isCustomer ? 'Nuevo cliente' : 'Nuevo proveedor' }}</a></div>
<section class="card"><div class="toolbar"><form class="filter-form" action="{{ route($kind.'.index') }}" method="GET"><div class="search-field">@include('partials.icon', ['name' => 'search'])<label class="sr-only" for="contact-search">Buscar {{ $isCustomer ? 'cliente' : 'proveedor' }}</label><input id="contact-search" class="input" name="q" value="{{ request('q') }}" placeholder="Nombre, documento o correo"></div><label class="sr-only" for="contact-status">Estado del contacto</label><select class="filter-select" id="contact-status" name="status"><option value="">Todos los estados</option><option value="active" @selected(request('status') === 'active')>Activos</option><option value="inactive" @selected(request('status') === 'inactive')>Inactivos</option></select><button class="button button-secondary button-small" type="submit">Buscar</button>@if(request('q') || request('status'))<a class="button-link" href="{{ route($kind.'.index') }}">Limpiar</a>@endif</form><span class="result-count">{{ $contacts->total() }} {{ mb_strtolower($title) }}</span></div>
@if($contacts->isEmpty())@include('partials.empty', ['icon' => $isCustomer ? 'users' : 'truck', 'heading' => request('q') ? 'No encontramos coincidencias' : ($isCustomer ? 'Hacé lugar a tus clientes' : 'Tus proveedores, bien organizados'), 'description' => request('q') ? 'Probá con otro nombre o documento.' : 'Agregá el primer contacto para registrar operaciones y llevar su cuenta corriente.', 'url' => route($kind.'.create'), 'action' => $isCustomer ? 'Nuevo cliente' : 'Nuevo proveedor'])
@else<div class="table-wrap"><table class="responsive-table"><thead><tr><th>{{ $isCustomer ? 'Cliente' : 'Proveedor' }}</th><th>Contacto</th><th>Documento</th><th class="text-right">Saldo</th><th>Estado</th><th class="text-right">Acciones</th></tr></thead><tbody>@foreach($contacts as $contact)<tr><td><div class="product-cell"><span class="contact-initial">{{ mb_strtoupper(mb_substr($contact->name, 0, 1)) }}</span><div><a class="row-title" href="{{ route($kind.'.show', $contact) }}">{{ $contact->name }}</a><span class="row-sub">{{ $contact->email ?: 'Sin correo' }}</span></div></div></td><td data-label="Contacto">{{ $contact->phone ?: '—' }}</td><td data-label="Documento">{{ $contact->document ?: '—' }}</td><td data-label="Saldo" class="text-right"><a class="money text-bold {{ $contact->balance_cents > 0 ? 'text-purple' : 'text-success' }}" href="{{ route($kind.'.show', $contact) }}">{{ \App\Services\Money::format($contact->balance_cents) }}</a></td><td data-label="Estado"><span class="badge {{ $contact->active ? 'badge-green' : 'badge-gray' }}">{{ $contact->active ? 'Activo' : 'Inactivo' }}</span></td><td class="row-action-cell"><div class="table-actions"><a class="icon-button" href="{{ route($kind.'.edit', $contact) }}" title="Editar" aria-label="Editar {{ $contact->name }}">@include('partials.icon', ['name' => 'edit'])</a><form action="{{ route($kind.'.destroy', $contact) }}" method="POST" data-confirm="¿Eliminar este contacto? Si tiene operaciones registradas, desactivalo desde la edición.">@csrf @method('DELETE')<button class="icon-button danger" type="submit" title="Eliminar" aria-label="Eliminar {{ $contact->name }}">@include('partials.icon', ['name' => 'trash'])</button></form></div></td></tr>@endforeach</tbody></table></div>@include('partials.pagination', ['paginator' => $contacts])@endif</section>
@endsection
