import {env as cloudflareEnv} from 'cloudflare:workers';
import type {Address,CartLine,Category,Order,Product,Session} from './domain';
import {seedCategories,seedProducts} from './seed';
import type {CommerceEnv} from './integrations';
export type StoreEnv=CommerceEnv & {DB?:D1Database;BUCKET?:R2Bucket;ADMIN_EMAILS?:string;SITE_URL?:string};
export class StoreError extends Error {constructor(message:string,public status=400){super(message);}}
export const runtime=()=>cloudflareEnv as unknown as StoreEnv;
export function database(){const db=runtime().DB;if(!db)throw new StoreError('La base de datos todavía no está disponible.',503);return db;}
export function session(request:Request):Session|null {const id=request.headers.get('oai-authenticated-user-id'),email=request.headers.get('oai-authenticated-user-email');if(!id||!email)return null;let name=request.headers.get('oai-authenticated-user-full-name')||email.split('@')[0];if(request.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8'){try{name=decodeURIComponent(name);}catch{}}const admins=(runtime().ADMIN_EMAILS||'').split(',').map(s=>s.trim().toLowerCase()).filter(Boolean);const local=process.env.NODE_ENV!=='production'&&id==='local_seedy'&&email==='seedy@sites.test';return{id,email,name,isAdmin:admins.includes(email.toLowerCase())||local};}
export function requireUser(request:Request){const user=session(request);if(!user)throw new StoreError('Ingresá con tu cuenta para continuar.',401);return user;}
export function requireAdmin(request:Request){const user=requireUser(request);if(!user.isAdmin)throw new StoreError('Esta sección está disponible para el administrador.',403);return user;}
export function mutation(request:Request){const origin=request.headers.get('origin');const expected=new URL(request.url).origin;const configured=runtime().SITE_URL;if(!origin||(origin!==expected&&origin!==configured))throw new StoreError('La solicitud debe hacerse desde la tienda.',403);}
export async function jsonBody(request:Request){if(Number(request.headers.get('content-length')||0)>256000)throw new StoreError('La solicitud es demasiado grande.',413);const raw=await request.text();if(raw.length>256000)throw new StoreError('La solicitud es demasiado grande.',413);try{return JSON.parse(raw);}catch{throw new StoreError('Revisá los datos enviados.');}}
export function text(value:unknown,label:string,max=160,required=true){if(typeof value!=='string') {if(!required)return '';throw new StoreError(`Completá ${label}.`);}const result=value.trim();if((required&&!result)||result.length>max)throw new StoreError(`Revisá ${label}.`);return result;}
export function numeric(value:unknown,label:string,min:number,max:number,integer=false){const n=Number(value);if(value===''||value==null||!Number.isFinite(n)||n<min||n>max||(integer&&!Number.isInteger(n)))throw new StoreError(`Revisá ${label}.`);return n;}
export function fail(error:unknown){if(error instanceof StoreError)return Response.json({error:error.message},{status:error.status});console.error('Store operation failed:',error instanceof Error?error.name:'unknown');return Response.json({error:'No pudimos completar la operación. Volvé a intentar.'},{status:500});}
export function response(value:unknown,status=200){return Response.json(value,{status,headers:{'Cache-Control':'no-store'}});}
export async function ensureSeed(){const db=database();const existing=await db.prepare("SELECT value FROM store_metadata WHERE key='catalog_seed_v1'").first();if(existing)return;const statements:D1PreparedStatement[]=[];for(const c of seedCategories)statements.push(db.prepare('INSERT OR IGNORE INTO categories(id,name,parent_id,slug) VALUES(?,?,?,?)').bind(c.id,c.name,c.parentId,c.slug));for(const p of seedProducts)statements.push(db.prepare('INSERT OR IGNORE INTO products(id,sku,name,brand,description,price,stock,category_id,active,featured,weight_grams,height_cm,width_cm,length_cm,media) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(p.id,p.sku,p.name,p.brand,p.description,p.price,p.stock,p.categoryId,1,1,p.weightGrams,p.heightCm,p.widthCm,p.lengthCm,JSON.stringify(p.media)));statements.push(db.prepare("INSERT OR IGNORE INTO store_metadata(key,value) VALUES('catalog_seed_v1','1')"));await db.batch(statements);}
export const productFromRow=(r:Record<string,unknown>):Product=>({id:String(r.id),sku:String(r.sku),name:String(r.name),brand:String(r.brand),description:String(r.description),price:Number(r.price),stock:Number(r.stock),categoryId:String(r.category_id),active:!!r.active,featured:!!r.featured,weightGrams:Number(r.weight_grams),heightCm:Number(r.height_cm),widthCm:Number(r.width_cm),lengthCm:Number(r.length_cm),media:JSON.parse(String(r.media||'[]'))});
export const orderFromRow=(r:Record<string,unknown>):Order=>({id:String(r.id),number:String(r.number),createdAt:String(r.created_at),status:String(r.status),paymentStatus:String(r.payment_status),total:Number(r.total),shippingCost:Number(r.shipping_cost),shippingMethod:String(r.shipping_method),trackingCode:r.tracking_code?String(r.tracking_code):null,trackingUrl:r.tracking_url?String(r.tracking_url):null,isDemo:!!r.is_demo,items:JSON.parse(String(r.items)),address:JSON.parse(String(r.address)),customerName:String(r.customer_name),customerEmail:String(r.customer_email),paymentUrl:r.payment_url?String(r.payment_url):null});
export async function catalog(includeInactive=false){await ensureSeed();const db=database();const [p,c]=await Promise.all([db.prepare(`SELECT * FROM products ${includeInactive?'':'WHERE active=1'} ORDER BY featured DESC,name`).all(),db.prepare('SELECT id,name,parent_id AS parentId,slug FROM categories ORDER BY name').all()]);return{products:p.results.map(productFromRow),categories:c.results as Category[]};}
export function integrationStatus(){const e=runtime();return{mercadopago:!!(e.MERCADOPAGO_ACCESS_TOKEN&&e.MERCADOPAGO_WEBHOOK_SECRET),zipnova:!!(e.ZIPNOVA_API_TOKEN&&e.ZIPNOVA_API_SECRET&&e.ZIPNOVA_ACCOUNT_ID&&e.ZIPNOVA_ORIGIN_ID)};}
export async function cartProducts(value:unknown){if(!Array.isArray(value)||!value.length||value.length>30)throw new StoreError('Agregá productos al carrito.');const ids=new Set<string>();const items:CartLine[]=value.map(line=>{if(!line||typeof line!=='object')throw new StoreError('Revisá el carrito.');const productId=text(line.productId,'el producto',80),quantity=numeric(line.quantity,'la cantidad',1,100,true);if(ids.has(productId))throw new StoreError('El carrito tiene productos repetidos.');ids.add(productId);return{productId,quantity};});const data=await catalog();for(const line of items){const p=data.products.find(p=>p.id===line.productId);if(!p||!p.active)throw new StoreError('Un producto del carrito ya no está disponible.',409);if(line.quantity>p.stock)throw new StoreError(`Quedan ${p.stock} unidades de ${p.name}.`,409);}return{items,products:data.products.filter(p=>ids.has(p.id))};}
export async function hashCart(items:CartLine[],products:Product[]){const stable=items.map(l=>{const p=products.find(p=>p.id===l.productId)!;return[l.productId,l.quantity,p.price,p.weightGrams,p.heightCm,p.widthCm,p.lengthCm];}).sort((a,b)=>String(a[0]).localeCompare(String(b[0])));const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(stable)));return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('');}
export function address(value:unknown):Address{if(!value||typeof value!=='object')throw new StoreError('Completá los datos de entrega.');const input=value as Record<string,unknown>;const result:Address={name:text(input.name,'tu nombre',100),email:text(input.email,'tu email',150),phone:text(input.phone,'tu teléfono',30),document:text(input.document,'tu documento',25,false),street:text(input.street,'la calle',150,false),number:text(input.number,'el número',20,false),floor:text(input.floor,'piso o departamento',60,false),city:text(input.city,'la localidad',100,false),state:text(input.state,'la provincia',100,false),postcode:text(input.postcode,'el código postal',12,false)};if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(result.email))throw new StoreError('Revisá el email.');return result;}
export function shipmentAddress(value:Address){if(!value.street||!value.number||!value.city||!value.state||!value.postcode||!value.document)throw new StoreError('Completá dirección, localidad, provincia, código postal y documento para el envío.');return value;}
export const safeUrl=(value:string|null)=>!value||(/^https:\/\//.test(value)&&value.length<2000);
