@extends('layouts.app')
@section('title', $product->exists ? 'Editar producto' : 'Nuevo producto')
@section('content')
<div class="page-heading"><div><div class="eyebrow">TU CATÁLOGO</div><h1>{{ $product->exists ? 'Editar producto' : 'Nuevo producto' }}</h1><p>{{ $product->exists ? 'Mantené la información y el stock actualizados.' : 'Cada gran venta empieza con un buen producto.' }}</p></div><a class="button button-secondary" href="{{ route('products.index') }}">@include('partials.icon', ['name' => 'back'])Volver</a></div>
<form action="{{ $product->exists ? route('products.update', $product) : route('products.store') }}" method="POST" enctype="multipart/form-data">@csrf @if($product->exists)@method('PUT')<input type="hidden" name="expected_stock" value="{{ old('expected_stock', $product->stock) }}">@endif
<div class="form-layout"><div class="form-main"><section class="card"><div class="card-header"><div><h2>Información del producto</h2><p>Los campos con * son obligatorios.</p></div><span class="stat-icon">@include('partials.icon', ['name' => 'box'])</span></div><div class="card-body"><div class="form-grid">
<div class="field span-2"><label for="name">Nombre <span class="required">*</span></label><input class="input" id="name" name="name" value="{{ old('name', $product->name) }}" maxlength="200" placeholder="Ej. Cuaderno A5 tapa dura" required>@error('name')<span class="field-error">{{ $message }}</span>@enderror</div>
<div class="field"><label for="sku">SKU / Código interno <span class="required">*</span></label><input class="input" id="sku" name="sku" value="{{ old('sku', $product->sku) }}" maxlength="80" placeholder="Ej. CUAD-001" required>@error('sku')<span class="field-error">{{ $message }}</span>@enderror</div>
<div class="field"><label for="barcode">Código de barras</label><input class="input" id="barcode" name="barcode" value="{{ old('barcode', $product->barcode) }}" maxlength="80" placeholder="Escaneá o ingresá el código"></div>
<div class="field"><label for="category">Categoría</label><input class="input" id="category" name="category" value="{{ old('category', $product->category) }}" maxlength="100" placeholder="Ej. Librería"></div>
<div class="field"><label for="supplier_id">Proveedor habitual</label><select id="supplier_id" name="supplier_id"><option value="">Sin proveedor asignado</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}" @selected((string)old('supplier_id', $product->supplier_id) === (string)$supplier->id)>{{ $supplier->name }}</option>@endforeach</select></div>
<div class="field span-2"><label for="description">Descripción</label><textarea id="description" name="description" rows="3" placeholder="Detalles que te ayudan a identificarlo">{{ old('description', $product->description) }}</textarea></div>
</div></div></section><section class="card section-gap"><div class="card-header"><div><h2>Precios y existencias</h2><p>Importes en pesos argentinos.</p></div></div><div class="card-body"><div class="form-grid">
<div class="field"><label for="cost">Precio de costo <span class="required">*</span></label><input class="input" id="cost" name="cost" inputmode="decimal" type="number" min="0" max="999999999.99" step="0.01" value="{{ old('cost', number_format(($product->cost_cents ?? 0) / 100, 2, '.', '')) }}" required><p class="hint">Lo que pagás por una unidad.</p></div>
<div class="field"><label for="price">Precio de venta <span class="required">*</span></label><input class="input" id="price" name="price" inputmode="decimal" type="number" min="0" max="999999999.99" step="0.01" value="{{ old('price', number_format(($product->price_cents ?? 0) / 100, 2, '.', '')) }}" required><p class="hint">Lo que cobrás por una unidad.</p></div>
<div class="field"><label for="stock">Stock actual <span class="required">*</span></label><input class="input" id="stock" name="stock" inputmode="numeric" type="number" min="0" max="100000000" step="1" value="{{ old('stock', $product->stock ?? 0) }}" required><p class="hint">Unidades disponibles. Las compras y ventas actualizan el stock.</p></div>
<div class="field"><label for="min_stock">Stock mínimo <span class="required">*</span></label><input class="input" id="min_stock" name="min_stock" inputmode="numeric" type="number" min="0" max="100000000" step="1" value="{{ old('min_stock', $product->min_stock ?? 0) }}" required><p class="hint">Te avisamos cuando el stock llega a este valor.</p></div>
<div class="span-2 toggle-field"><input type="hidden" name="active" value="0"><input type="checkbox" id="active" name="active" value="1" @checked(old('active', $product->exists ? $product->active : true))><label for="active">Producto activo<small>Disponible para nuevas ventas y compras.</small></label></div>
</div></div></section><div class="form-actions"><a class="button button-secondary" href="{{ route('products.index') }}">Cancelar</a><button class="button button-primary" type="submit">@include('partials.icon', ['name' => 'check'])Guardar producto</button></div></div><aside><section class="card"><div class="card-header"><h2>Imagen del producto</h2></div><div class="card-body"><div class="image-upload">@if($product->image_path)<img class="image-preview" src="{{ asset('storage/'.$product->image_path) }}" alt="{{ $product->name }}"><br>@else
@include('partials.icon', ['name' => 'image'])
@endif
<p>Una imagen vale mil productos.<br>JPG, PNG o WebP · hasta 2 MB</p><label class="sr-only" for="image">Imagen del producto</label><input id="image" type="file" name="image" accept="image/jpeg,image/png,image/webp"></div>@error('image')<span class="field-error">{{ $message }}</span>@enderror</div></section><div class="info-panel section-gap">@include('partials.icon', ['name' => 'heart'])<h3>Un catálogo bien cuidado</h3><p>Usá nombres claros y códigos únicos. Encontrarás cada producto más rápido al registrar una venta.</p></div></aside></div></form>
@endsection
