@php
    $purchase = $kind === 'purchases';
    $labels = ['cash' => 'Efectivo', 'card' => 'Tarjeta', 'transfer' => 'Transferencia', 'account' => 'Cuenta corriente'];
@endphp
<div class="page-heading"><div><div class="eyebrow">{{ $purchase ? 'ABASTECÉ TU TIENDA' : 'CADA VENTA CUENTA' }}</div><h1>{{ $purchase ? 'Compras' : 'Ventas' }}</h1><p>{{ $purchase ? 'Registrá mercadería y mantené el stock al día.' : 'Consultá tus operaciones y registrá una nueva venta.' }}</p></div><a class="button button-primary" href="{{ route($kind.'.create') }}">@include('partials.icon', ['name' => 'plus']){{ $purchase ? 'Nueva compra' : 'Nueva venta' }}</a></div>
<section class="card">
    <div class="toolbar"><form class="filter-form" method="GET" action="{{ route($kind.'.index') }}"><div class="search-field">@include('partials.icon', ['name' => 'search'])<label for="order-search" class="sr-only">Buscar {{ $purchase ? 'compra' : 'venta' }}</label><input class="input" id="order-search" name="q" value="{{ request('q') }}" placeholder="Número o {{ $purchase ? 'proveedor' : 'cliente' }}"></div><label class="sr-only" for="order-status">Estado</label><select class="filter-select" id="order-status" name="status"><option value="">Todos los estados</option><option value="completed" @selected(request('status') === 'completed')>Registradas</option><option value="cancelled" @selected(request('status') === 'cancelled')>Anuladas</option></select><button class="button button-secondary button-small" type="submit">Buscar</button>@if(request('q') || request('status'))<a class="button-link" href="{{ route($kind.'.index') }}">Limpiar</a>@endif</form><span class="result-count">{{ $records->total() }} {{ $purchase ? 'compras' : 'ventas' }}</span></div>
    @if($records->isEmpty())
        @include('partials.empty', ['icon' => $purchase ? 'cart' : 'bag', 'heading' => request('q') || request('status') ? 'No encontramos operaciones' : ($purchase ? 'Tu próxima compra empieza acá' : 'Tu primera venta empieza acá'), 'description' => request('q') || request('status') ? 'Probá con otra búsqueda o cambiá el estado.' : ($purchase ? 'Agregá los productos recibidos y actualizá tu stock.' : 'Elegí los productos, el cliente y cómo te va a pagar.'), 'url' => route($kind.'.create'), 'action' => $purchase ? 'Registrar compra' : 'Registrar venta'])
    @else
        <div class="table-wrap"><table class="responsive-table"><thead><tr><th>Operación</th><th>{{ $purchase ? 'Proveedor' : 'Cliente' }}</th><th>Forma de pago</th><th class="text-right">Total</th><th>Estado</th><th class="text-right">Detalle</th></tr></thead><tbody>
        @foreach($records as $record)
            <tr><td><a class="row-title" href="{{ route($kind.'.show', $record) }}">{{ $record->number }}</a><span class="row-sub">{{ $record->created_at->format('d/m/Y · H:i') }}</span></td><td data-label="{{ $purchase ? 'Proveedor' : 'Cliente' }}">{{ $purchase ? ($record->supplier?->name ?? 'Proveedor eliminado') : ($record->customer?->name ?? 'Consumidor final') }}</td><td data-label="Forma de pago"><span class="badge {{ $record->payment_method === 'account' ? 'badge-purple' : 'badge-gray' }}">{{ $labels[$record->payment_method] ?? $record->payment_method }}</span></td><td class="text-right money text-bold" data-label="Total">{{ \App\Services\Money::format($record->total_cents) }}</td><td data-label="Estado"><span class="badge {{ $record->status === 'cancelled' ? 'badge-orange' : 'badge-green' }}">{{ $record->status === 'cancelled' ? 'Anulada' : 'Registrada' }}</span></td><td class="row-action-cell"><a class="icon-button" href="{{ route($kind.'.show', $record) }}" aria-label="Ver {{ $record->number }}" title="Ver detalle">@include('partials.icon', ['name' => 'arrow'])</a></td></tr>
        @endforeach
        </tbody></table></div>@include('partials.pagination', ['paginator' => $records])
    @endif
</section>
