@php
    $purchase = $kind === 'purchases';
    $labels = ['cash' => 'Efectivo', 'card' => 'Tarjeta', 'transfer' => 'Transferencia', 'account' => 'Cuenta corriente'];
    $contact = $purchase ? $record->supplier : $record->customer;
@endphp
<div class="page-heading"><div><div class="eyebrow">{{ $purchase ? 'INGRESO DE MERCADERÍA' : 'COMPROBANTE DE VENTA' }}</div><h1>{{ $record->number }}</h1><p>{{ $record->status === 'cancelled' ? 'Esta operación fue anulada.' : ($purchase ? 'La mercadería ya está en tu stock.' : 'Venta registrada correctamente.') }}</p></div><div class="heading-actions"><a class="button button-secondary" href="{{ route($kind.'.index') }}">@include('partials.icon', ['name' => 'back'])Volver</a><button class="button button-secondary" type="button" data-print>@include('partials.icon', ['name' => 'print'])Imprimir</button></div></div>
<div class="receipt"><section class="card receipt-card"><div class="card-body">
    <div class="receipt-heading"><div>@if($storeBrand['logo_url'])<img class="receipt-logo" src="{{ $storeBrand['logo_url'] }}" alt="Logo de {{ $storeBrand['name'] }}">@endif<div class="receipt-brand">{{ $storeBrand['name'] }}</div><p class="muted">{{ $purchase ? 'Registro de compra' : 'Comprobante interno de venta' }}</p></div><div class="receipt-meta"><strong>{{ $record->number }}</strong><p>{{ $record->created_at->format('d/m/Y · H:i') }}</p><p><span class="badge {{ $record->status === 'cancelled' ? 'badge-orange' : 'badge-green' }}">{{ $record->status === 'cancelled' ? 'Anulada' : 'Registrada' }}</span></p></div></div>
    <div class="receipt-info"><div><span>{{ $purchase ? 'Proveedor' : 'Cliente' }}</span><strong>{{ $contact?->name ?? ($purchase ? 'Proveedor eliminado' : 'Consumidor final') }}</strong>@if($contact?->document)<span>{{ $contact->document }}</span>@endif</div><div><span>Forma de pago</span><strong>{{ $labels[$record->payment_method] ?? $record->payment_method }}</strong></div><div><span>Registrado por</span><strong>{{ $record->user?->name ?? 'Usuario eliminado' }}</strong></div></div>
    <div class="receipt-table"><table><thead><tr><th>Producto</th><th class="text-right">Cantidad</th><th class="text-right">{{ $purchase ? 'Costo unitario' : 'Precio unitario' }}</th><th class="text-right">Subtotal</th></tr></thead><tbody>@foreach($record->items as $item)<tr><td><span class="row-title">{{ $item->name }}</span><span class="row-sub">{{ $item->sku }}</span></td><td class="text-right">{{ $item->quantity }}</td><td class="text-right money">{{ \App\Services\Money::format($purchase ? $item->unit_cost_cents : $item->unit_price_cents) }}</td><td class="text-right money text-bold">{{ \App\Services\Money::format($item->subtotal_cents) }}</td></tr>@endforeach</tbody></table></div>
    <div class="receipt-total"><span>Total {{ $purchase ? 'de la compra' : 'de la venta' }}</span><span class="money">{{ \App\Services\Money::format($record->total_cents) }}</span></div>
    @if($record->payment_method === 'account')<p class="receipt-notes">{{ $purchase ? 'El importe se registró en la cuenta corriente del proveedor.' : 'El importe se registró en la cuenta corriente del cliente.' }}</p>@endif
    @if($record->cancelled_at)<p class="receipt-notes">Anulada el {{ $record->cancelled_at->format('d/m/Y · H:i') }}.</p>@endif
    <p class="receipt-footer">Registro interno de {{ $storeBrand['name'] }} · No válido como factura fiscal.</p>
</div></section>
@if($record->status !== 'cancelled')<div class="form-actions no-print"><a class="button button-primary" href="{{ route($kind.'.create') }}">@include('partials.icon', ['name' => 'plus']){{ $purchase ? 'Nueva compra' : 'Nueva venta' }}</a><form action="{{ route($kind.'.cancel', $record) }}" method="POST" data-confirm="{{ $purchase ? '¿Anular esta compra? Se descontará el stock recibido y se compensará la cuenta corriente si correspondía.' : '¿Anular esta venta? Se repondrá el stock y se compensará la cuenta corriente si correspondía.' }}">@csrf<button class="button button-danger" type="submit">@include('partials.icon', ['name' => 'close']){{ $purchase ? 'Anular compra' : 'Anular venta' }}</button></form></div>@endif
</div>
